name: python_excel

dependencies:
  - conda
  - jupyterlab
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyexcel
  - python
  - xlrd
  - pip:
    - pyexcel-xls
    - pyexcel-xlsx
    - pylightxl
    - qrcode
    - xlsxwriter
    - xlwt
