name: python_excel
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - ipywidgets
  - jupyterlab
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyexcel
  - python=3.8
  - xlrd
  - pip:
    - pyexcel-xls
    - pyexcel-xlsx
    - pylightxl
    - qrcode
    - xlsxwriter
    - xlwt
