name: python_excel
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - ipywidgets
  - jupyterlab
  - jupytext
  - nbconvert
  - nodejs=13
  - nbstripout
  - numpy
  - openpyxl
  - pandas
  - pip
  - pip:
    - -r file:requirements.txt
  - pyexcel
  - python=3.8
  - xlrd
  - xlsxwriter
  - xlwt
